name: Docker Image CI
run-name: Push image to Docker Hub (PR \#${{ github.event.number }}) by @${{ github.event.sender.login }}

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the image 
      run: docker build . --file Dockerfile --tag vgafib/web-ggj:${{ github.sha }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push image
      run: |
        docker push vgafib/web-ggj:${{ github.event.number }}
        docker image tag vgafib/web-ggj:${{ github.event.number }} vgafib/web-ggj:latest
        docker push vgafib/web-ggj:latest
        
    - name: Cleanup
      run: docker rmi vgafib/web-ggj:${{ github.event.number }} vgafib/web-ggj:latest
        
